/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CotizacionTokenRouteImport } from './routes/cotizacion.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedQuotationsIndexRouteImport } from './routes/_authenticated/quotations/index'
import { Route as AuthenticatedQuotationsNewRouteImport } from './routes/_authenticated/quotations/new'
import { Route as AuthenticatedQuotationsIdRouteImport } from './routes/_authenticated/quotations/$id'
import { Route as AuthenticatedQuotationsIdEditRouteImport } from './routes/_authenticated/quotations/$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CotizacionTokenRoute = CotizacionTokenRouteImport.update({
  id: '/cotizacion/$token',
  path: '/cotizacion/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotationsIndexRoute =
  AuthenticatedQuotationsIndexRouteImport.update({
    id: '/quotations/',
    path: '/quotations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsNewRoute =
  AuthenticatedQuotationsNewRouteImport.update({
    id: '/quotations/new',
    path: '/quotations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIdRoute =
  AuthenticatedQuotationsIdRouteImport.update({
    id: '/quotations/$id',
    path: '/quotations/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotationsIdEditRoute =
  AuthenticatedQuotationsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedQuotationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/cotizacion/$token': typeof CotizacionTokenRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRouteWithChildren
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/quotations/$id/edit': typeof AuthenticatedQuotationsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/cotizacion/$token': typeof CotizacionTokenRoute
  '/quotations/$id': typeof AuthenticatedQuotationsIdRouteWithChildren
  '/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/quotations': typeof AuthenticatedQuotationsIndexRoute
  '/quotations/$id/edit': typeof AuthenticatedQuotationsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/cotizacion/$token': typeof CotizacionTokenRoute
  '/_authenticated/quotations/$id': typeof AuthenticatedQuotationsIdRouteWithChildren
  '/_authenticated/quotations/new': typeof AuthenticatedQuotationsNewRoute
  '/_authenticated/quotations/': typeof AuthenticatedQuotationsIndexRoute
  '/_authenticated/quotations/$id/edit': typeof AuthenticatedQuotationsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/settings'
    | '/cotizacion/$token'
    | '/quotations/$id'
    | '/quotations/new'
    | '/quotations/'
    | '/quotations/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/settings'
    | '/cotizacion/$token'
    | '/quotations/$id'
    | '/quotations/new'
    | '/quotations'
    | '/quotations/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/settings'
    | '/cotizacion/$token'
    | '/_authenticated/quotations/$id'
    | '/_authenticated/quotations/new'
    | '/_authenticated/quotations/'
    | '/_authenticated/quotations/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CotizacionTokenRoute: typeof CotizacionTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cotizacion/$token': {
      id: '/cotizacion/$token'
      path: '/cotizacion/$token'
      fullPath: '/cotizacion/$token'
      preLoaderRoute: typeof CotizacionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/': {
      id: '/_authenticated/quotations/'
      path: '/quotations'
      fullPath: '/quotations/'
      preLoaderRoute: typeof AuthenticatedQuotationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/new': {
      id: '/_authenticated/quotations/new'
      path: '/quotations/new'
      fullPath: '/quotations/new'
      preLoaderRoute: typeof AuthenticatedQuotationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id': {
      id: '/_authenticated/quotations/$id'
      path: '/quotations/$id'
      fullPath: '/quotations/$id'
      preLoaderRoute: typeof AuthenticatedQuotationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotations/$id/edit': {
      id: '/_authenticated/quotations/$id/edit'
      path: '/edit'
      fullPath: '/quotations/$id/edit'
      preLoaderRoute: typeof AuthenticatedQuotationsIdEditRouteImport
      parentRoute: typeof AuthenticatedQuotationsIdRoute
    }
  }
}

interface AuthenticatedQuotationsIdRouteChildren {
  AuthenticatedQuotationsIdEditRoute: typeof AuthenticatedQuotationsIdEditRoute
}

const AuthenticatedQuotationsIdRouteChildren: AuthenticatedQuotationsIdRouteChildren =
  {
    AuthenticatedQuotationsIdEditRoute: AuthenticatedQuotationsIdEditRoute,
  }

const AuthenticatedQuotationsIdRouteWithChildren =
  AuthenticatedQuotationsIdRoute._addFileChildren(
    AuthenticatedQuotationsIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedQuotationsIdRoute: typeof AuthenticatedQuotationsIdRouteWithChildren
  AuthenticatedQuotationsNewRoute: typeof AuthenticatedQuotationsNewRoute
  AuthenticatedQuotationsIndexRoute: typeof AuthenticatedQuotationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedQuotationsIdRoute: AuthenticatedQuotationsIdRouteWithChildren,
  AuthenticatedQuotationsNewRoute: AuthenticatedQuotationsNewRoute,
  AuthenticatedQuotationsIndexRoute: AuthenticatedQuotationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CotizacionTokenRoute: CotizacionTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
