ALTER TABLE public.resources
  ADD COLUMN IF NOT EXISTS coverage_scope text,
  ADD COLUMN IF NOT EXISTS address text,
  ADD COLUMN IF NOT EXISTS postal_code text,
  ADD COLUMN IF NOT EXISTS latitude numeric,
  ADD COLUMN IF NOT EXISTS longitude numeric,
  ADD COLUMN IF NOT EXISTS meeting_point text,
  ADD COLUMN IF NOT EXISTS pickup_location text,
  ADD COLUMN IF NOT EXISTS dropoff_location text,
  ADD COLUMN IF NOT EXISTS geo_radius_km integer,
  ADD COLUMN IF NOT EXISTS operating_zone text,
  ADD COLUMN IF NOT EXISTS rental_requires_driver boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS rental_min_age integer,
  ADD COLUMN IF NOT EXISTS rental_license_required text,
  ADD COLUMN IF NOT EXISTS rental_deposit_amount numeric,
  ADD COLUMN IF NOT EXISTS rental_deposit_currency text NOT NULL DEFAULT 'ARS',
  ADD COLUMN IF NOT EXISTS rental_included_km integer,
  ADD COLUMN IF NOT EXISTS rental_extra_km_cost numeric,
  ADD COLUMN IF NOT EXISTS rental_fuel_policy text,
  ADD COLUMN IF NOT EXISTS rental_vehicle_condition text;